// Auto-generated by check-links.mjs — do not edit by hand.
window.LINKS_DATA = {
  "checked_at": "2026-06-22T23:34:01.494Z",
  "collected_at": "2026-06-22T22:35:48.892Z",
  "timeout_ms": 10000,
  "total_urls": 424,
  "sites": [
    {
      "name": "OTI",
      "url": "https://www.nyc.gov/content/oti/pages/home",
      "counts": {
        "ok": 423,
        "review": 1,
        "broken": 0
      },
      "links": [
        {
          "href": "https://www.facebook.com/NYCOfficeofTech/",
          "text": "Facebook",
          "kind": "external",
          "status": 400,
          "state": "review",
          "page_count": 40,
          "pages": [
            "https://www.nyc.gov/content/oti/pages/",
            "https://www.nyc.gov/content/oti/pages/who-we-are",
            "https://www.nyc.gov/content/oti/pages/our-work-2",
            "https://www.nyc.gov/content/oti/pages/news-reports",
            "https://www.nyc.gov/content/oti/pages/contact",
            "https://www.nyc.gov/content/oti/pages/new-yorkers",
            "https://www.nyc.gov/content/oti/pages/businesses",
            "https://www.nyc.gov/content/oti/pages/government-partners",
            "https://www.nyc.gov/content/oti/pages/tools",
            "https://www.nyc.gov/content/oti/pages/working-at-oti",
            "https://www.nyc.gov/content/oti/pages/internships",
            "https://www.nyc.gov/content/oti/pages/fellowships",
            "https://www.nyc.gov/content/oti/pages/recent-appearances",
            "https://www.nyc.gov/content/oti/pages/big-apple-connect",
            "https://www.nyc.gov/content/oti/pages/build-a-connected-city",
            "https://www.nyc.gov/content/oti/pages/advance-digital-service-delivery",
            "https://www.nyc.gov/content/oti/pages/harness-the-power-of-data",
            "https://www.nyc.gov/content/oti/pages/tech-innovation-for-all",
            "https://www.nyc.gov/content/oti/pages/enhance-technology-resiliency",
            "https://www.nyc.gov/content/oti/pages/oti-website-accessibility",
            "https://www.nyc.gov/content/oti/pages/open-data",
            "https://www.nyc.gov/content/oti/pages/nyc-top-level-domain",
            "https://www.nyc.gov/content/oti/pages/broadband",
            "https://www.nyc.gov/content/oti/pages/meet-the-team",
            "https://www.nyc.gov/content/oti/pages/interagency-mous"
          ]
        }
      ]
    }
  ]
};
